### ISSUE TITLE
Incorrect Return Type.

### ISSUE THREAD

**Issue by codiemorgan** [Phylliida/UnityMatrix#1]
https://github.com/Phylliida/UnityMatrix/blob/fbc80ff7ba11408a6a5e631ea7734f2ce4637202/Matrix.cs#L214

I'm pretty it was intended to use Vector4 as the return type here on line 214. In return-cast W component is lost due to cast to Vector3.

**Comment by Phylliida** [comment]
Fixed! Thanks :)

**Comment by codiemorgan** [comment]
\0/ no problem. Just a random thing I came across while looking at different matrix implementations.
