### ISSUE TITLE
Matrix.cs line 31 has coordinates reversed

### ISSUE THREAD

**Issue by pixelpax** [Phylliida/UnityMatrix#2]
I believe it should be 

     mat[j][i] = values[j][i];
instead of 
        
     mat[i][j] = values[i][j];

In this case, i has been chosen to represent columns and this matrix implementation is row-first.

**Comment by Phylliida** [comment]
Good catch! See the attached commit for my preferred fix, that would have had an out of bounds error for a non-square matrix (but for a square matrix it wouldn't have mattered)
